#!/bin/bash

jsonresponse=$(aws elasticbeanstalk describe-environment-resources --environment-name Rabbitmqcluster-dev)

autscalinggroupname=`echo $jsonresponse | jq ".EnvironmentResources.AutoScalingGroups[].Name"`

echo $autscalinggroupname

DNSES=$(aws ec2 describe-instances --filters "Name=tag:aws:autoscaling:groupName,Values=$autscalinggroupname" "Name=instance-state-name,Values=running" | jq ".Reservations[].Instances[].PrivateDnsName" | xargs)

echo $DNSES
