#!/bin/bash

jsonresponse=$(aws elasticbeanstalk describe-environment-resources --environment-name Rabbitmqcluster-dev)

autscalinggroupname=`echo $jsonresponse | jq ".EnvironmentResources.AutoScalingGroups[].Name"`

echo $autscalinggroupname

